name: weather
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  intl: ^0.18.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
